#!/usr/bin/env python3
"""
EdgeIQ Labs Security Report Generator
Version: 1.0.0

Aggregates scan output from EdgeIQ tools (XSS Scanner, Network Scanner,
SSL Watcher, Alerting System) into professional HTML/TEXT/JSON reports
delivered by email, Telegram, or file output.

Stdlib only — no pip dependencies.
"""

import argparse
import datetime
import email.encoders
import email.mime.base
import email.mime.multipart
import email.mime.text
import hashlib
import html
import json
import os
import re
import smtplib
import socket
import ssl
import sys
import time
import uuid
from pathlib import Path
from typing import Any, Optional

# ─── Constants ────────────────────────────────────────────────────────────────

BRAND_FOOTER = (
    "EdgeIQ Labs Security Report | "
    "Generated by EdgeIQ Labs Security Report Generator v1.0.0 | "
    "For internal use only. Not for redistribution."
)

HTML_HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif; background: #0f1117; color: #e0e6ed; line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 40px 24px; }}
  .header {{ background: linear-gradient(135deg, #1a1f2e 0%, #141820 100%); border: 1px solid #2a3042; border-radius: 12px; padding: 40px; margin-bottom: 32px; }}
  .brand-logo {{ font-size: 28px; font-weight: 700; color: #00d4ff; letter-spacing: 1px; margin-bottom: 8px; }}
  .brand-sub {{ font-size: 14px; color: #7a8499; text-transform: uppercase; letter-spacing: 2px; }}
  .report-title {{ font-size: 32px; font-weight: 700; color: #ffffff; margin: 24px 0 8px; }}
  .report-meta {{ font-size: 13px; color: #7a8499; margin-bottom: 24px; }}
  .score-badge {{ display: inline-block; padding: 12px 28px; border-radius: 8px; font-size: 18px; font-weight: 700; margin-top: 16px; }}
  .score-low {{ background: #0d3b2e; color: #00c97a; border: 1px solid #00c97a; }}
  .score-medium {{ background: #3b2e0d; color: #ffb800; border: 1px solid #ffb800; }}
  .score-high {{ background: #3b0d0d; color: #ff4757; border: 1px solid #ff4757; }}
  .score-critical {{ background: #3b0d0d; color: #ff2244; border: 2px solid #ff2244; }}
  .score-minimal {{ background: #0d3b2e; color: #00c97a; border: 1px solid #00c97a; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-top: 24px; }}
  .summary-card {{ background: #1a1f2e; border: 1px solid #2a3042; border-radius: 8px; padding: 20px; text-align: center; }}
  .summary-number {{ font-size: 36px; font-weight: 700; color: #00d4ff; }}
  .summary-label {{ font-size: 12px; color: #7a8499; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }}
  .severity-bar {{ display: flex; gap: 8px; margin-top: 16px; justify-content: center; flex-wrap: wrap; }}
  .sev-pill {{ padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }}
  .sev-critical {{ background: #ff2244; color: #fff; }}
  .sev-high {{ background: #ff4757; color: #fff; }}
  .sev-medium {{ background: #ffb800; color: #111; }}
  .sev-low {{ background: #00c97a; color: #111; }}
  .sev-info {{ background: #3498db; color: #fff; }}
  h2 {{ font-size: 20px; font-weight: 700; color: #ffffff; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #2a3042; }}
  .finding {{ background: #141820; border: 1px solid #2a3042; border-radius: 8px; margin-bottom: 12px; overflow: hidden; }}
  .finding-header {{ padding: 16px 20px; display: flex; align-items: flex-start; gap: 12px; }}
  .finding-sev {{ width: 10px; height: 10px; border-radius: 50%; margin-top: 6px; flex-shrink: 0; }}
  .finding-title {{ font-size: 15px; font-weight: 600; color: #e0e6ed; flex: 1; }}
  .finding-meta {{ font-size: 12px; color: #7a8499; margin-top: 2px; }}
  .finding-body {{ padding: 0 20px 16px 42px; font-size: 14px; color: #a0a8b8; line-height: 1.7; }}
  .code-block {{ background: #0a0d14; border: 1px solid #2a3042; border-radius: 6px; padding: 14px 18px; font-family: 'Courier New', monospace; font-size: 13px; color: #a8d8ff; overflow-x: auto; margin: 10px 0; }}
  .rec-card {{ background: #1a1f2e; border: 1px solid #2a3042; border-radius: 8px; padding: 20px; margin-bottom: 12px; display: flex; gap: 16px; align-items: flex-start; }}
  .rec-priority {{ width: 40px; height: 40px; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 18px; font-weight: 700; flex-shrink: 0; }}
  .rec-content {{ flex: 1; }}
  .rec-title {{ font-size: 15px; font-weight: 600; color: #e0e6ed; margin-bottom: 4px; }}
  .rec-detail {{ font-size: 13px; color: #7a8499; }}
  .section-empty {{ color: #4a5568; font-style: italic; padding: 16px 0; }}
  .footer {{ text-align: center; font-size: 11px; color: #4a5568; margin-top: 48px; padding-top: 24px; border-top: 1px solid #2a3042; line-height: 1.8; }}
  .alert-badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }}
  .alert-critical {{ background: #ff2244; color: #fff; }}
  .alert-high {{ background: #ff4757; color: #fff; }}
  .alert-medium {{ background: #ffb800; color: #111; }}
  .alert-low {{ background: #00c97a; color: #111; }}
  .alert-info {{ background: #3498db; color: #fff; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 14px; margin: 16px 0; }}
  th {{ background: #1a1f2e; color: #7a8499; text-align: left; padding: 10px 16px; border-bottom: 1px solid #2a3042; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
  td {{ padding: 12px 16px; border-bottom: 1px solid #1e2533; color: #c0c8d4; }}
  tr:last-child td {{ border-bottom: none; }}
  .target-section {{ background: #141820; border: 1px solid #2a3042; border-radius: 8px; margin-bottom: 24px; overflow: hidden; }}
  .target-header {{ background: #1a1f2e; padding: 16px 24px; border-bottom: 1px solid #2a3042; font-size: 18px; font-weight: 700; color: #00d4ff; }}
</style>
</head>
<body>
<div class="container">
"""

HTML_FOOTER = """
  <div class="footer">{footer}</div>
</div>
</body>
</html>
"""

# ─── Globals for delivery callbacks ───────────────────────────────────────────

_report_targets_data: Optional[dict] = None

# ─── Helpers ──────────────────────────────────────────────────────────────────

def load_config(path: str) -> dict:
    with open(path, 'r') as f:
        return json.load(f)

def load_json_file(path: str) -> Any:
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None

def now_iso() -> str:
    return datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

def severity_color(sev: str) -> str:
    colors = {
        'critical': '#ff2244',
        'high': '#ff4757',
        'medium': '#ffb800',
        'low': '#00c97a',
        'info': '#3498db',
    }
    return colors.get(sev.lower(), '#7a8499')

def severity_pill_class(sev: str) -> str:
    return f'sev-{sev.lower()}'

def alert_badge_class(sev: str) -> str:
    return f'alert-{sev.lower()}'

def risk_score_to_label(score: int) -> str:
    if score >= 80:
        return 'critical'
    elif score >= 60:
        return 'high'
    elif score >= 40:
        return 'medium'
    elif score >= 20:
        return 'low'
    return 'minimal'

def compute_risk_score(finding_counts: dict) -> int:
    """Weighted risk score 0-100. critical=25, high=18, medium=10, low=4, info=2."""
    weights = {'critical': 25, 'high': 18, 'medium': 10, 'low': 4, 'info': 2}
    score = sum(weights.get(sev.lower(), 0) * count for sev, count in finding_counts.items())
    return min(score, 100)

def html_escape(s: str) -> str:
    return html.escape(str(s), quote=True)

def parse_target(target_str: str) -> dict:
    target = target_str.strip().rstrip('/')
    if target.startswith('http://') or target.startswith('https://'):
        return {'url': target, 'domain': target.split('/')[2]}
    return {'domain': target, 'url': f'https://{target}'}

# ─── Input Directory Scanner ────────────────────────────────────────────────────

def scan_input_directory(scan_dir: str) -> dict:
    """
    Walk scan_dir for JSON files produced by EdgeIQ tools.
    Files named: xss_{target}.json, network_{target}.json,
                 ssl_{target}.json, alert_{target}.json
    Returns dict: { target: { 'xss': [], 'network': {}, 'ssl': {}, 'alerts': [] } }
    """
    targets: dict = {}
    scan_path = Path(scan_dir)
    if not scan_path.exists():
        return targets

    for json_file in sorted(scan_path.glob('*.json')):
        data = load_json_file(str(json_file))
        if not data:
            continue

        stem = json_file.stem.lower()
        tool: Optional[str] = None
        target_name = json_file.stem

        if stem.startswith('xss_'):
            tool = 'xss'
            target_name = stem[4:]
        elif stem.startswith('network_'):
            tool = 'network'
            target_name = stem[8:]
        elif stem.startswith('ssl_') or stem.startswith('cert_'):
            tool = 'ssl'
            target_name = stem[4:] if stem.startswith('ssl_') else stem[5:]
        elif stem.startswith('alert_'):
            tool = 'alerts'
            target_name = stem[6:]
        else:
            tool = data.get('tool', data.get('type', '')).lower()
            target_name = data.get('target', data.get('host', data.get('domain', json_file.stem)))

        if target_name not in targets:
            targets[target_name] = {'xss': [], 'network': None, 'ssl': None, 'alerts': []}

        if tool == 'xss':
            targets[target_name]['xss'].extend(data.get('findings', data.get('vulnerabilities', [])))
        elif tool == 'network':
            targets[target_name]['network'] = data
        elif tool == 'ssl':
            targets[target_name]['ssl'] = data
        elif tool == 'alerts':
            targets[target_name]['alerts'].extend(data.get('alerts', data.get('events', [])))

    return targets

# ─── Report Data Builders ─────────────────────────────────────────────────────

def build_executive_summary(targets_data: dict) -> dict:
    sev_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
    total_issues = 0
    xss_total = 0
    open_ports = 0
    ssl_issues = 0
    alert_count = 0
    targets_scanned = len(targets_data)

    for target, data in targets_data.items():
        for finding in data.get('xss', []):
            sev = finding.get('severity', 'medium').lower()
            sev_counts[sev] = sev_counts.get(sev, 0) + 1
            total_issues += 1
            xss_total += 1

        if data.get('network'):
            for port in data['network'].get('open_ports', []):
                open_ports += 1
                sev = port.get('severity', 'medium').lower()
                sev_counts[sev] = sev_counts.get(sev, 0) + 1
                total_issues += 1
            for cve in data['network'].get('cves', []):
                sev = cve.get('severity', 'high').lower()
                sev_counts[sev] = sev_counts.get(sev, 0) + 1
                total_issues += 1

        if data.get('ssl'):
            for issue in data['ssl'].get('issues', []):
                ssl_issues += 1
                sev = issue.get('severity', 'medium').lower()
                sev_counts[sev] = sev_counts.get(sev, 0) + 1
                total_issues += 1

        alert_count += len(data.get('alerts', []))

    risk_score = compute_risk_score(sev_counts)
    risk_label = risk_score_to_label(risk_score)

    return {
        'generated_at': now_iso(),
        'targets_scanned': targets_scanned,
        'total_issues': total_issues,
        'risk_score': risk_score,
        'risk_label': risk_label,
        'severity_breakdown': sev_counts,
        'xss_findings': xss_total,
        'open_ports': open_ports,
        'ssl_issues': ssl_issues,
        'alert_count': alert_count,
    }

def build_xss_section(targets_data: dict) -> list:
    findings = []
    order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
    for target, data in targets_data.items():
        for f in data.get('xss', []):
            findings.append({
                'target': target,
                'url': f.get('url', target),
                'vulnerability': f.get('vulnerability', f.get('type', 'Unknown')),
                'severity': f.get('severity', 'medium'),
                'description': f.get('description', ''),
                'payload': f.get('payload', ''),
                'parameter': f.get('parameter', f.get('param', '')),
                'evidence': f.get('evidence', ''),
            })
    findings.sort(key=lambda x: order.get(x['severity'].lower(), 5))
    return findings

def build_network_section(targets_data: dict) -> list:
    sections = []
    for target, data in targets_data.items():
        if not data.get('network'):
            continue
        net = data['network']
        sections.append({
            'target': target,
            'ip': net.get('ip', net.get('host', '')),
            'open_ports': sorted(net.get('open_ports', []), key=lambda p: p.get('port', 0)),
            'cves': net.get('cves', []),
            'os_detection': net.get('os', net.get('os_detection', '')),
            'service_versions': net.get('service_versions', {}),
        })
    return sections

def build_ssl_section(targets_data: dict) -> list:
    sections = []
    for target, data in targets_data.items():
        if not data.get('ssl'):
            continue
        ssl_data = data['ssl']
        sections.append({
            'target': target,
            'domain': ssl_data.get('domain', target),
            'issuer': ssl_data.get('issuer', ''),
            'valid_from': ssl_data.get('valid_from', ''),
            'valid_until': ssl_data.get('valid_until', ''),
            'days_until_expiry': ssl_data.get('days_until_expiry', 0),
            'protocol_version': ssl_data.get('protocol_version', 'TLS 1.2'),
            'grade': ssl_data.get('grade', 'N/A'),
            'issues': ssl_data.get('issues', []),
            'headers': ssl_data.get('security_headers', {}),
        })
    return sections

def build_alerts_section(targets_data: dict) -> list:
    all_alerts = []
    order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
    for target, data in targets_data.items():
        for alert in data.get('alerts', []):
            alert_copy = dict(alert)
            alert_copy['target'] = target
            all_alerts.append(alert_copy)
    all_alerts.sort(key=lambda x: order.get(x.get('severity', 'medium').lower(), 5))
    return all_alerts

def build_recommendations(exec_summary: dict, xss_data: list, network_data: list,
                           ssl_data: list, alert_data: list) -> list:
    recs = []
    sev_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}

    critical_xss = [f for f in xss_data if f['severity'].lower() in ('critical', 'high')]
    if critical_xss:
        recs.append({
            'priority': 1, 'severity': 'critical',
            'title': 'Address Critical/High XSS Vulnerabilities Immediately',
            'detail': (f'{len(critical_xss)} critical or high severity cross-site scripting vulnerabilities found. '
                      'These can lead to session hijacking, credential theft, and defacement. '
                      'Implement input sanitization and output encoding. Consider deploying a WAF as temporary mitigation.'),
        })

    critical_cves = [c for section in network_data for c in section.get('cves', [])
                     if c.get('severity', '').lower() in ('critical', 'high')]
    if critical_cves:
        recs.append({
            'priority': 2, 'severity': 'critical',
            'title': 'Patch Critical CVEs Within 24-48 Hours',
            'detail': (f'{len(critical_cves)} critical or high severity CVEs detected. '
                      'Prioritize patching by CVSS score. Subscribe to CVE feeds and patch systematically.'),
        })

    ssl_critical = [f"{s['target']}: {i.get('title', 'SSL issue')}"
                    for s in ssl_data for i in s.get('issues', [])
                    if i.get('severity', '').lower() in ('critical', 'high')]
    if ssl_critical:
        recs.append({
            'priority': 3, 'severity': 'critical',
            'title': 'Fix Critical SSL/TLS Configuration Issues',
            'detail': f'{len(ssl_critical)} critical SSL issues: ' + '; '.join(ssl_critical[:5]),
        })

    expiring = [s for s in ssl_data if s.get('days_until_expiry', 999) <= 30]
    if expiring:
        recs.append({
            'priority': 4, 'severity': 'high',
            'title': 'Renew Expiring SSL Certificates',
            'detail': (f'{len(expiring)} certificate(s) expiring within 30 days. '
                      'Renew before expiry to avoid service disruptions.'),
        })

    sensitive = [f"{p['port']}/{p['service']}" for section in network_data
                  for p in section.get('open_ports', [])
                  if p.get('service', '').lower() in ('ssh', 'ftp', 'telnet', 'rdp', 'mysql')]
    if sensitive:
        recs.append({
            'priority': 5, 'severity': 'medium',
            'title': 'Restrict Access to Sensitive Services',
            'detail': (f'Exposed sensitive ports: {", ".join(sensitive[:8])}. '
                      'Restrict via firewall rules, VPN, or jump hosts.'),
        })

    if alert_data:
        critical_alerts = [a for a in alert_data if a.get('severity', '').lower() in ('critical', 'high')]
        if critical_alerts:
            recs.append({
                'priority': 6, 'severity': 'high',
                'title': 'Review Triggered Security Alerts',
                'detail': f'{len(critical_alerts)} critical/high alerts generated. '
                          'Review alert history in the EdgeIQ Alerting System dashboard.',
            })

    if not recs:
        recs.append({
            'priority': 1, 'severity': 'low',
            'title': 'Continue Monitoring — No Critical Issues Found',
            'detail': 'All scanned targets passed with no critical or high severity findings. '
                      'Maintain regular scanning cadence to catch emerging issues.',
        })

    recs.sort(key=lambda x: (sev_order.get(x['severity'].lower(), 5), x['priority']))
    return recs

# ─── Output Generators ─────────────────────────────────────────────────────────

def generate_text_report(exec_summary: dict, xss_data: list, network_data: list,
                         ssl_data: list, alert_data: list, recs: list,
                         targets_data: dict) -> str:
    lines = []
    lines.append("=" * 70)
    lines.append("EDGEIQ LABS — SECURITY REPORT")
    lines.append("=" * 70)
    lines.append(f"Generated: {exec_summary['generated_at']}")
    lines.append(f"Targets Scanned: {exec_summary['targets_scanned']}")
    lines.append(f"Overall Risk Score: {exec_summary['risk_score']}/100 ({exec_summary['risk_label'].upper()})")
    lines.append("")

    sb = exec_summary['severity_breakdown']
    lines.append("── Severity Breakdown ──────────────────────────────")
    for sev in ('critical', 'high', 'medium', 'low', 'info'):
        count = sb.get(sev, 0)
        if count:
            lines.append(f"  [{sev.upper():8}] {count}")
    lines.append("")

    if xss_data:
        lines.append("── XSS Findings ─────────────────────────────────────")
        for f in xss_data:
            lines.append(f"  [{f['severity'].upper():8}] {f['vulnerability']}")
            lines.append(f"  Target: {f['target']} | URL: {f['url']}")
            if f.get('parameter'):
                lines.append(f"  Parameter: {f['parameter']}")
            if f.get('payload'):
                lines.append(f"  Payload: {f['payload']}")
            if f.get('description'):
                lines.append(f"  {f['description']}")
            lines.append("")
    else:
        lines.append("── XSS Findings: None")
        lines.append("")

    if network_data:
        lines.append("── Network Findings ────────────────────────────────")
        for section in network_data:
            lines.append(f"  Target: {section['target']} ({section.get('ip', 'N/A')})")
            if section.get('open_ports'):
                lines.append(f"  Open Ports ({len(section['open_ports'])}):")
                for p in section['open_ports'][:20]:
                    lines.append(f"    {p.get('port','?')}/{p.get('protocol','tcp')} - "
                                 f"{p.get('service','unknown')} (severity: {p.get('severity','medium')})")
            if section.get('cves'):
                lines.append(f"  CVEs ({len(section['cves'])}):")
                for c in section['cves'][:10]:
                    lines.append(f"    {c.get('cve_id','N/A')} - {c.get('description','')[:70]}")
            lines.append("")
    else:
        lines.append("── Network Findings: None")
        lines.append("")

    if ssl_data:
        lines.append("── SSL/Certificate Findings ────────────────────────")
        for section in ssl_data:
            lines.append(f"  Domain: {section['domain']} | Grade: {section['grade']}")
            lines.append(f"  Issuer: {section['issuer']}")
            lines.append(f"  Valid Until: {section['valid_until']} ({section.get('days_until_expiry','?')} days)")
            if section.get('issues'):
                for issue in section['issues']:
                    lines.append(f"  Issue: [{issue.get('severity','?').upper()}] {issue.get('title','N/A')}")
            lines.append("")
    else:
        lines.append("── SSL/Certificate Findings: None")
        lines.append("")

    if alert_data:
        lines.append(f"── Alert History ({len(alert_data)} events) ───────────────")
        for a in alert_data[:20]:
            lines.append(f"  [{a.get('severity','?').upper():8}] {a.get('title', a.get('name','N/A'))}")
            lines.append(f"  Target: {a.get('target','N/A')} | Time: {a.get('timestamp', a.get('time','N/A'))}")
            lines.append("")
    else:
        lines.append("── Alert History: No alerts recorded")
        lines.append("")

    lines.append("── Recommendations ────────────────────────────────")
    for r in recs:
        lines.append(f"  Priority {r['priority']} [{r['severity'].upper():8}] {r['title']}")
        lines.append(f"  {r['detail']}")
        lines.append("")

    lines.append(BRAND_FOOTER)
    return "\n".join(lines)

def generate_html_report(exec_summary: dict, xss_data: list, network_data: list,
                        ssl_data: list, alert_data: list, recs: list,
                        targets_data: dict, title: str = "Security Report") -> str:
    sb = exec_summary['severity_breakdown']
    score_class = f"score-{exec_summary['risk_label']}"
    sev_pills = "".join(
        f'<span class="sev-pill {severity_pill_class(sev)}">{sev.upper()} × {sb.get(sev, 0)}</span>'
        for sev in ('critical', 'high', 'medium', 'low', 'info') if sb.get(sev, 0)
    )

    # XSS
    if xss_data:
        xss_html = ""
        for f in xss_data:
            color = severity_color(f['severity'])
            xss_html += f"""
        <div class="finding">
          <div class="finding-header">
            <div class="finding-sev" style="background:{color}"></div>
            <div>
              <div class="finding-title">{html_escape(f['vulnerability'])}</div>
              <div class="finding-meta">{html_escape(f['target'])} | {html_escape(f.get('url', ''))}</div>
            </div>
            <span class="alert-badge {alert_badge_class(f['severity'])}">{f['severity'].upper()}</span>
          </div>
          <div class="finding-body">
            {html_escape(f.get('description', ''))}
            {('<div class="code-block">Parameter: ' + html_escape(f.get('parameter', '')) + '</div>') if f.get('parameter') else ''}
            {('<div class="code-block">Payload: ' + html_escape(f.get('payload', '')) + '</div>') if f.get('payload') else ''}
            {('<div class="code-block">Evidence: ' + html_escape(f.get('evidence', '')) + '</div>') if f.get('evidence') else ''}
          </div>
        </div>"""
    else:
        xss_html = '<div class="section-empty">No XSS vulnerabilities detected.</div>'

    # Network
    if network_data:
        net_html = ""
        for section in network_data:
            net_html += (f'<div class="target-section">'
                         f'<div class="target-header">{html_escape(section["target"])} '
                         f'({html_escape(section.get("ip", "N/A"))})</div>')
            if section.get('open_ports'):
                net_html += ('<table><tr><th>Port</th><th>Protocol</th><th>Service</th>'
                             '<th>Version</th><th>Severity</th></tr>')
                for p in section['open_ports']:
                    sev = p.get('severity', 'medium')
                    net_html += (f"<tr><td>{p.get('port','?')}</td><td>{p.get('protocol','tcp')}</td>"
                                 f"<td>{html_escape(p.get('service','unknown'))}</td>"
                                 f"<td>{html_escape(p.get('version',''))}</td>"
                                 f"<td><span class='alert-badge {alert_badge_class(sev)}'>{sev.upper()}</span></td></tr>")
                net_html += '</table>'
            if section.get('cves'):
                net_html += ('<table><tr><th>CVE ID</th><th>Description</th>'
                             '<th>CVSS</th><th>Severity</th></tr>')
                for c in section['cves']:
                    sev = c.get('severity', 'high')
                    net_html += (f"<tr><td><code>{html_escape(c.get('cve_id','N/A'))}</code></td>"
                                 f"<td>{html_escape(c.get('description','')[:80])}</td>"
                                 f"<td>{c.get('cvss','N/A')}</td>"
                                 f"<td><span class='alert-badge {alert_badge_class(sev)}'>{sev.upper()}</span></td></tr>")
                net_html += '</table>'
            net_html += '</div>'
    else:
        net_html = '<div class="section-empty">No network scan data present.</div>'

    # SSL
    if ssl_data:
        ssl_html = ""
        for section in ssl_data:
            days = section.get('days_until_expiry', 999)
            exp_cls = ('alert-critical' if days <= 7 else
                       'alert-medium' if days <= 30 else 'alert-low')
            issues_html = ""
            if section.get('issues'):
                issues_html = '<p><strong>Issues:</strong></p><ul>'
                for issue in section['issues']:
                    issues_html += (f"<li>[{issue.get('severity','?').upper()}] "
                                    f"{html_escape(issue.get('title','N/A'))} — "
                                    f"{html_escape(issue.get('description',''))}</li>")
                issues_html += '</ul>'
            else:
                issues_html = '<p>No issues detected.</p>'

            headers_html = ""
            if section.get('headers'):
                headers_html = '<p><strong>Headers:</strong></p><ul>'
                for k, v in section['headers'].items():
                    headers_html += f"<li><code>{html_escape(str(k))}</code>: {html_escape(str(v))}</li>"
                headers_html += '</ul>'

            ssl_html += f"""
        <div class="finding">
          <div class="finding-header">
            <div class="finding-sev" style="background:{severity_color('medium')}"></div>
            <div>
              <div class="finding-title">{html_escape(section['domain'])}</div>
              <div class="finding-meta">Issuer: {html_escape(section.get('issuer','N/A'))} | Grade: <strong>{section.get('grade','N/A')}</strong></div>
            </div>
            <span class="alert-badge {exp_cls}">Exp: {days}d</span>
          </div>
          <div class="finding-body">
            <p><strong>Valid:</strong> {section.get('valid_from','?')} → {section.get('valid_until','?')}</p>
            <p><strong>Protocol:</strong> {html_escape(section.get('protocol_version','TLS'))}</p>
            {headers_html}
            {issues_html}
          </div>
        </div>"""
    else:
        ssl_html = '<div class="section-empty">No SSL scan data present.</div>'

    # Alerts
    if alert_data:
        alerts_html = ('<table><tr><th>Time</th><th>Alert</th><th>Target</th><th>Severity</th></tr>')
        for a in alert_data:
            sev = a.get('severity', 'info')
            alerts_html += (f"<tr><td>{html_escape(str(a.get('timestamp', a.get('time','N/A'))))}</td>"
                            f"<td>{html_escape(a.get('title', a.get('name','N/A')))}</td>"
                            f"<td>{html_escape(a.get('target','N/A'))}</td>"
                            f"<td><span class='alert-badge {alert_badge_class(sev)}'>{sev.upper()}</span></td></tr>")
        alerts_html += '</table>'
    else:
        alerts_html = '<div class="section-empty">No alerts triggered in this period.</div>'

    # Recommendations
    rec_pri_colors = {'critical': '#ff2244', 'high': '#ff4757', 'medium': '#ffb800', 'low': '#00c97a'}
    rec_html = ""
    for r in recs:
        color = rec_pri_colors.get(r['severity'].lower(), '#7a8499')
        rec_html += f"""
        <div class="rec-card">
          <div class="rec-priority" style="background:{color};color:#fff">{r['priority']}</div>
          <div class="rec-content">
            <div class="rec-title">[{r['severity'].upper()}] {html_escape(r['title'])}</div>
            <div class="rec-detail">{html_escape(r['detail'])}</div>
          </div>
        </div>"""

    body = f"""
  <div class="header">
    <div class="brand-logo">⬡ EdgeIQ Labs</div>
    <div class="brand-sub">Security Intelligence Platform</div>
    <div class="report-title">{html_escape(title)}</div>
    <div class="report-meta">Generated: {exec_summary['generated_at']} UTC &nbsp;·&nbsp; {exec_summary['targets_scanned']} target(s) scanned</div>
    <div><span class="score-badge {score_class}">Risk Score: {exec_summary['risk_score']}/100 — {exec_summary['risk_label'].upper()}</span></div>
    <div class="summary-grid">
      <div class="summary-card"><div class="summary-number">{exec_summary['total_issues']}</div><div class="summary-label">Total Issues</div></div>
      <div class="summary-card"><div class="summary-number">{exec_summary['xss_findings']}</div><div class="summary-label">XSS Findings</div></div>
      <div class="summary-card"><div class="summary-number">{exec_summary['open_ports']}</div><div class="summary-label">Open Ports</div></div>
      <div class="summary-card"><div class="summary-number">{exec_summary['alert_count']}</div><div class="summary-label">Alerts</div></div>
    </div>
    <div class="severity-bar">{sev_pills}</div>
  </div>

  <h2>① Executive Summary</h2>
  <div class="finding">
    <div class="finding-body">
      <p>This report covers <strong>{exec_summary['targets_scanned']}</strong> target(s) scanned by EdgeIQ Labs security tools.
      A total of <strong>{exec_summary['total_issues']}</strong> issue(s) were identified with an overall risk score of
      <strong>{exec_summary['risk_score']}/100</strong> ({exec_summary['risk_label'].upper()}).
      {'Immediate action is recommended.' if exec_summary['risk_score'] >= 60 else ' Findings should be addressed in a timely manner.'}</p>
    </div>
  </div>

  <h2>② XSS Findings ({len(xss_data)})</h2>
  {xss_html}

  <h2>③ Network Findings ({len(network_data)} hosts scanned)</h2>
  {net_html}

  <h2>④ SSL / Certificate Findings ({len(ssl_data)})</h2>
  {ssl_html}

  <h2>⑤ Alert History ({len(alert_data)} events)</h2>
  {alerts_html}

  <h2>⑥ Recommendations</h2>
  {rec_html}

  <div class="footer">{html_escape(BRAND_FOOTER)}</div>
"""
    return HTML_HEADER.format(title=html_escape(title)) + body + HTML_FOOTER.format(footer=html_escape(BRAND_FOOTER))

def generate_json_report(exec_summary: dict, xss_data: list, network_data: list,
                          ssl_data: list, alert_data: list, recs: list,
                          targets_data: dict) -> dict:
    return {
        'version': '1.0.0',
        'generated_at': exec_summary['generated_at'],
        'tool': 'edgeiq-security-report-generator',
        'executive_summary': exec_summary,
        'findings': {
            'xss': xss_data,
            'network': network_data,
            'ssl': ssl_data,
            'alerts': alert_data,
        },
        'recommendations': recs,
    }

# ─── Delivery ───────────────────────────────────────────────────────────────────

def deliver_email(report_content: str, subject: str, config: dict,
                   fmt: str, exec_summary: dict) -> bool:
    """Send report via SMTP. Returns True on success."""
    smtp_conf = config.get('delivery', {}).get('smtp', {})
    if not smtp_conf.get('enabled'):
        return False
    try:
        msg = email.mime.multipart.MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = smtp_conf.get('from', 'security@edgeiq.io')
        msg['To'] = ', '.join(smtp_conf.get('to', []))

        if fmt == 'html':
            msg.attach(email.mime.text.MIMEText(report_content, 'html'))
            # Plain fallback
            plain = generate_text_report(exec_summary, [], [], [], [], [], {})
            msg.attach(email.mime.text.MIMEText(plain, 'plain'))
        else:
            msg.attach(email.mime.text.MIMEText(report_content, 'plain'))

        if smtp_conf.get('attachments') and fmt == 'html':
            part = email.mime.base.MIMEBase('application', 'octet-stream')
            part.set_payload(report_content.encode('utf-8'))
            email.encoders.encode_base64(part)
            part.add_header('Content-Disposition', 'attachment', filename='security_report.html')
            msg.attach(part)

        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_conf.get('host', 'localhost'),
                          smtp_conf.get('port', 587), timeout=30) as server:
            server.starttls(context=context)
            if smtp_conf.get('username') and smtp_conf.get('password'):
                server.login(smtp_conf['username'], smtp_conf['password'])
            server.sendmail(smtp_conf['from'], smtp_conf['to'], msg.as_string())
        return True
    except Exception as e:
        print(f"[EMAIL ERROR] {e}", file=sys.stderr)
        return False

def deliver_telegram(report_content: str, config: dict,
                     fmt: str, exec_summary: dict) -> bool:
    """Send report summary via Telegram bot. Returns True on success."""
    tg_conf = config.get('delivery', {}).get('telegram', {})
    if not tg_conf.get('enabled') or not tg_conf.get('bot_token'):
        return False
    try:
        import urllib.request
        import urllib.parse

        text = (f"🛡️ EdgeIQ Labs Security Report\n"
                f"Risk Score: {exec_summary.get('risk_score', 'N/A')}/100\n"
                f"Issues Found: {exec_summary.get('total_issues', 0)}\n"
                f"Targets: {exec_summary.get('targets_scanned', 0)}\n")

        url = f"https://api.telegram.org/bot{tg_conf['bot_token']}/sendMessage"
        data = urllib.parse.urlencode({
            'chat_id': tg_conf.get('chat_id', tg_conf.get('target_chat_id', '')),
            'text': text,
            'parse_mode': 'HTML',
        }).encode()
        req = urllib.request.Request(url, data=data)
        with urllib.request.urlopen(req, timeout=15) as resp:
            json.loads(resp.read())
        return True
    except Exception as e:
        print(f"[TELEGRAM ERROR] {e}", file=sys.stderr)
        return False

# ─── Subprocess Tool Runner ─────────────────────────────────────────────────────

def run_edgeiq_tool(tool_script: str, target: str, timeout: int = 120) -> dict:
    """Run an EdgeIQ tool script as a subprocess. Returns JSON dict or error dict."""
    import shutil
    import subprocess

    if not shutil.which('python3'):
        return {'error': 'python3 not found', 'tool': tool_script}

    try:
        result = subprocess.run(
            ['python3', tool_script, '--target', target, '--json'],
            capture_output=True, text=True, timeout=timeout,
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
        return {'error': f'exit {result.returncode}', 'stderr': result.stderr[:500]}
    except subprocess.TimeoutExpired:
        return {'error': 'timeout', 'tool': tool_script, 'target': target}
    except FileNotFoundError:
        return {'error': 'script not found', 'tool': tool_script}
    except json.JSONDecodeError:
        return {'error': 'invalid JSON output', 'tool': tool_script}

# ─── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='EdgeIQ Labs Security Report Generator')
    parser.add_argument('--config', default='config.json', help='Path to config JSON file')
    parser.add_argument('--format', choices=['html', 'text', 'json'], default='html', help='Output format')
    parser.add_argument('--delivery', choices=['email', 'telegram', 'file', 'both'], default='file', help='Delivery method')
    parser.add_argument('--targets', nargs='*', help='Override target list from config')
    parser.add_argument('--input-dir', help='Override scan input directory')
    parser.add_argument('--output-dir', help='Override output directory')
    parser.add_argument('--title', default='Monthly Security Report', help='Report title')
    parser.add_argument('--throttle-ms', type=int, default=1000, help='Delay between targets (ms)')
    parser.add_argument('--no-run-scans', action='store_true', help='Skip running EdgeIQ tool subprocesses')
    args = parser.parse_args()

    config = load_config(args.config)

    scan_dir = args.input_dir or config.get('scan_input_dir', 'input/scans')
    output_dir = args.output_dir or config.get('output', {}).get('path', 'output')
    target_list = args.targets or config.get('targets', [])
    os.makedirs(output_dir, exist_ok=True)

    # Gather scan data from input directory
    targets_data: dict = {}
    dir_scan_data = scan_input_directory(scan_dir)
    for target_name, data in dir_scan_data.items():
        targets_data[target_name] = data

    # Run EdgeIQ tool subprocesses if configured
    if not args.no_run_scans and target_list:
        tool_map = config.get('edgeiq_tools', {})
        for target in target_list:
            target_info = parse_target(target)
            tname = target_info['domain']
            if tname not in targets_data:
                targets_data[tname] = {'xss': [], 'network': None, 'ssl': None, 'alerts': []}

            xss_script = tool_map.get('xss_scanner', '')
            if xss_script and os.path.exists(xss_script):
                result = run_edgeiq_tool(xss_script, target)
                if result and 'error' not in result:
                    targets_data[tname]['xss'].extend(result.get('findings', result.get('vulnerabilities', [])))
                time.sleep(args.throttle_ms / 1000)

            net_script = tool_map.get('network_scanner', '')
            if net_script and os.path.exists(net_script):
                result = run_edgeiq_tool(net_script, target)
                if result and 'error' not in result:
                    targets_data[tname]['network'] = result
                time.sleep(args.throttle_ms / 1000)

            ssl_script = tool_map.get('ssl_watcher', '')
            if ssl_script and os.path.exists(ssl_script):
                result = run_edgeiq_tool(ssl_script, target)
                if result and 'error' not in result:
                    targets_data[tname]['ssl'] = result
                time.sleep(args.throttle_ms / 1000)

    # Build report sections
    global _report_targets_data
    _report_targets_data = targets_data

    exec_summary = build_executive_summary(targets_data)
    xss_data = build_xss_section(targets_data)
    network_data = build_network_section(targets_data)
    ssl_data = build_ssl_section(targets_data)
    alert_data = build_alerts_section(targets_data)
    recs = build_recommendations(exec_summary, xss_data, network_data, ssl_data, alert_data)

    # Generate output
    if args.format == 'html':
        report_content = generate_html_report(exec_summary, xss_data, network_data, ssl_data, alert_data, recs, targets_data, args.title)
        ext = 'html'
    elif args.format == 'text':
        report_content = generate_text_report(exec_summary, xss_data, network_data, ssl_data, alert_data, recs, targets_data)
        ext = 'txt'
    else:
        report_content = json.dumps(generate_json_report(exec_summary, xss_data, network_data, ssl_data, alert_data, recs, targets_data), indent=2)
        ext = 'json'

    timestamp = datetime.datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    report_filename = f"security_report_{timestamp}.{ext}"
    report_path = os.path.join(output_dir, report_filename)

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    print(f"Report written to: {report_path}")

    # Delivery
    subject = (f"EdgeIQ Labs Security Report — {args.title} "
               f"({exec_summary['risk_score']}/100 {exec_summary['risk_label'].upper()})")

    if args.delivery in ('email', 'both'):
        ok = deliver_email(report_content, subject, config, args.format, exec_summary)
        print(f"Email delivery: {'✓' if ok else '✗'}")

    if args.delivery in ('telegram', 'both'):
        ok = deliver_telegram(report_content, config, args.format, exec_summary)
        print(f"Telegram delivery: {'✓' if ok else '✗'}")

    print(f"Done. {exec_summary['total_issues']} issues found, risk score: {exec_summary['risk_score']}/100")

if __name__ == '__main__':
    main()